{
  "docs": "https://docs.ansible.com/ansible/2.11/dev_guide/testing/sanity/runtime-metadata.html",
  "results": [
    {
      "message": "The test `ansible-test sanity --test runtime-metadata` [[explain](https://docs.ansible.com/ansible/2.11/dev_guide/testing/sanity/runtime-metadata.html)] failed with the error:",
      "output": "Command \"/home/nchakrab/.virtualenvs/test/bin/python /home/nchakrab/.virtualenvs/test/lib/python3.9/site-packages/ansible_test/_data/sanity/code-smell/runtime-metadata.py\" returned exit status 1.\n>>> Standard Error\nTraceback (most recent call last):\n  File \"/home/nchakrab/.virtualenvs/test/lib/python3.9/site-packages/ansible_test/_data/sanity/code-smell/runtime-metadata.py\", line 15, in <module>\n    from voluptuous import All, Any, MultipleInvalid, PREVENT_EXTRA\nModuleNotFoundError: No module named 'voluptuous'"
    }
  ],
  "verified": false
}
